"""
PDF Exporter Module for SmartEDA
Generates comprehensive PDF analysis reports using FPDF2.
"""

import io
import os
import tempfile
from typing import Dict, Any, Optional
import pandas as pd
import plotly.graph_objects as go
import plotly.io as pio

try:
    from fpdf import FPDF, XPos, YPos
    FPDF_AVAILABLE = True
except ImportError:
    FPDF_AVAILABLE = False


class SmartEDAPDF(FPDF):
    """
    Custom FPDF2 class for SmartEDA PDF reports.
    Handles header and footer consistently.
    """

    def header(self):
        # Background bar
        self.set_fill_color(18, 17, 40)
        self.rect(0, 0, 210, 18, "F")
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(108, 99, 255)
        self.set_y(4)
        self.cell(0, 10, "SmartEDA  |  Automated EDA Report", align="C")
        self.set_draw_color(108, 99, 255)
        self.set_line_width(0.5)
        self.line(10, 18, 200, 18)
        self.ln(6)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 180)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by SmartEDA", align="C")

    def section_title(self, title: str):
        self.ln(4)
        self.set_fill_color(30, 28, 60)
        self.set_draw_color(108, 99, 255)
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(168, 164, 255)
        self.cell(0, 9, f"  {title}", new_x=XPos.LMARGIN, new_y=YPos.NEXT, fill=True, border="L")
        self.ln(2)

    def body_text(self, text: str, size: int = 9):
        self.set_font("Helvetica", "", size)
        self.set_text_color(220, 220, 240)
        self.multi_cell(0, 5, text)
        self.ln(1)

    def kv_line(self, key: str, value: str):
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(168, 164, 255)
        self.cell(60, 6, f"  {key}:")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(220, 220, 240)
        self.cell(0, 6, str(value), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    def table_from_df(self, df: pd.DataFrame, max_rows: int = 30):
        """Render a DataFrame as a simple PDF table."""
        if df.empty:
            self.body_text("No data available.")
            return

        df_display = df.head(max_rows)
        cols = df_display.columns.tolist()
        n_cols = len(cols)
        col_width = 180 / n_cols

        # Header row
        self.set_fill_color(30, 28, 60)
        self.set_font("Helvetica", "B", 7)
        self.set_text_color(168, 164, 255)
        for col in cols:
            self.cell(col_width, 7, str(col)[:18], border=1, fill=True, align="C")
        self.ln()

        # Data rows
        self.set_font("Helvetica", "", 7)
        for i, (_, row) in enumerate(df_display.iterrows()):
            self.set_fill_color(22, 20, 46) if i % 2 == 0 else self.set_fill_color(28, 26, 55)
            self.set_text_color(220, 220, 240)
            for col in cols:
                val = str(row[col])
                if len(val) > 18:
                    val = val[:15] + "..."
                self.cell(col_width, 6, val, border=1, fill=True, align="C")
            self.ln()
        self.ln(2)


def _fig_to_temp_image(fig: go.Figure, width: int = 900, height: int = 400) -> Optional[str]:
    """Export a Plotly figure to a temporary PNG file. Returns the file path."""
    try:
        tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".png")
        tmp.close()
        pio.write_image(fig, tmp.name, width=width, height=height, scale=1.5)
        return tmp.name
    except Exception:
        return None


def generate_pdf_report(
    profile: Dict[str, Any],
    df: pd.DataFrame,
    insights_text: Optional[str],
    corr_fig: Optional[go.Figure],
    missing_fig: Optional[go.Figure],
    dist_figs: list,
    outlier_iqr: Optional[Dict],
    filename: str = "smarteda_report.pdf",
) -> bytes:
    """
    Generate a full PDF analysis report.

    Returns the PDF as bytes (suitable for Streamlit's download_button).
    """
    if not FPDF_AVAILABLE:
        raise ImportError("fpdf2 is not installed. Run: pip install fpdf2")

    pdf = SmartEDAPDF()
    pdf.set_margins(10, 22, 10)
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # ── Cover Info ───────────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(108, 99, 255)
    pdf.cell(0, 12, "SmartEDA", align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(200, 200, 220)
    pdf.cell(0, 7, "LLM-Powered Automated Exploratory Data Analysis Report",
             align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(6)

    # ── Dataset Overview ─────────────────────────────────────────────────────
    pdf.section_title("1. Dataset Overview")
    pdf.kv_line("Rows", f"{profile['n_rows']:,}")
    pdf.kv_line("Columns", str(profile['n_cols']))
    pdf.kv_line("Memory Usage", f"{profile['memory_usage_mb']} MB")
    pdf.kv_line("Duplicate Rows", f"{profile['duplicate_count']} ({profile['duplicate_pct']}%)")
    pdf.kv_line("Numeric Columns", str(len(profile['column_types']['numeric'])))
    pdf.kv_line("Categorical Columns", str(len(profile['column_types']['categorical'])))

    # Column type list
    if profile['column_types']['numeric']:
        pdf.kv_line("Numeric", ", ".join(profile['column_types']['numeric'][:10]))
    if profile['column_types']['categorical']:
        pdf.kv_line("Categorical", ", ".join(profile['column_types']['categorical'][:10]))

    # ── Missing Values ───────────────────────────────────────────────────────
    pdf.section_title("2. Missing Values Summary")
    missing_df = profile['missing_info']
    has_missing = missing_df[missing_df["Missing Count"] > 0]
    if has_missing.empty:
        pdf.body_text("✓ No missing values detected in this dataset.")
    else:
        pdf.table_from_df(has_missing[["Column", "Missing Count", "Missing %", "Data Type"]])

    # ── Descriptive Statistics ───────────────────────────────────────────────
    pdf.section_title("3. Descriptive Statistics")
    desc = profile['desc_stats']
    if not desc.empty:
        pdf.table_from_df(desc)
    else:
        pdf.body_text("No numeric columns available.")

    # ── Correlation Summary ──────────────────────────────────────────────────
    pdf.section_title("4. Top Correlations")
    top_corr = profile['top_correlations']
    if not top_corr.empty:
        pdf.table_from_df(top_corr)
    else:
        pdf.body_text("No strong correlations (|r| ≥ 0.5) detected.")

    # ── Outlier Summary ──────────────────────────────────────────────────────
    pdf.section_title("5. Outlier Detection Summary (IQR Method)")
    if outlier_iqr and not outlier_iqr.get("summary", pd.DataFrame()).empty:
        pdf.kv_line("Total Flagged Rows", str(outlier_iqr.get("n_flagged", 0)))
        pdf.table_from_df(outlier_iqr["summary"][["Column", "Lower Bound", "Upper Bound", "Outlier Count", "Outlier %"]])
    else:
        pdf.body_text("Outlier detection not performed or no outliers found.")

    # ── AI Insights ──────────────────────────────────────────────────────────
    if insights_text:
        pdf.add_page()
        pdf.section_title("6. AI-Generated Insights (Google Gemini)")
        # Strip markdown symbols for PDF plain text
        clean_text = insights_text
        for sym in ["##", "**", "__", "```", "`", "###"]:
            clean_text = clean_text.replace(sym, "")
        clean_text = clean_text.replace("#", "").strip()
        pdf.body_text(clean_text[:6000])  # cap at 6000 chars

    # ── Charts ───────────────────────────────────────────────────────────────
    chart_page_added = False

    def _add_chart_page():
        nonlocal chart_page_added
        if not chart_page_added:
            pdf.add_page()
            pdf.section_title("7. Visualizations")
            chart_page_added = True

    # Correlation heatmap
    if corr_fig is not None:
        img_path = _fig_to_temp_image(corr_fig, width=900, height=500)
        if img_path and os.path.exists(img_path):
            _add_chart_page()
            pdf.body_text("Correlation Heatmap:")
            pdf.image(img_path, w=180)
            pdf.ln(4)
            try:
                os.unlink(img_path)
            except Exception:
                pass

    # Missing values chart
    if missing_fig is not None:
        img_path = _fig_to_temp_image(missing_fig, width=900, height=400)
        if img_path and os.path.exists(img_path):
            _add_chart_page()
            pdf.body_text("Missing Values Chart:")
            pdf.image(img_path, w=180)
            pdf.ln(4)
            try:
                os.unlink(img_path)
            except Exception:
                pass

    # Distribution histograms (first 4 only for PDF size)
    for i, (col_name, fig) in enumerate(dist_figs[:4]):
        img_path = _fig_to_temp_image(fig, width=900, height=420)
        if img_path and os.path.exists(img_path):
            _add_chart_page()
            pdf.body_text(f"Distribution: {col_name}")
            pdf.image(img_path, w=180)
            pdf.ln(4)
            try:
                os.unlink(img_path)
            except Exception:
                pass

    # Return as bytes
    return bytes(pdf.output())
